### ISSUE TITLE
Test Data

### ISSUE THREAD

**Issue by bobbycho** [guofengw/GOSTracker#1]
Hi,

Thank you for sharing your great work. If you do me a favor, I would like to ask you the test data, cube.avi and obj files.

Thanks,
Bobby

**Comment by jmxntg** [comment]
Hi,

could you please share the cube.avi, bunny.avi test videos please?

Best regards,

Joao Teixeira

**Comment by guofengw** [comment]
@bobbycho @jmxntg You can find the data in the data folder
