### ISSUE TITLE
The pose

### ISSUE THREAD

**Issue by CNchence** [guofengw/GOSTracker#2]
程序运行前，要输入首帧的pose，请问这个pose如何得到？

**Comment by guofengw** [comment]
一种简单的做法可以参考如下：你可以大致估计一个pose值，然后看算法能不能迭代到正确的pose，不行的话，重新调整pose值，直到算法可以得出首帧的值，然后把这个值作为初值，继续跟踪。

**Comment by guofengw** [comment]
@CNchence 一种简单的做法可以参考如下：你可以大致估计一个pose值，然后看算法能不能迭代到正确的pose，不行的话，重新调整pose值，直到算法可以得出首帧的值，然后把这个值作为初值，继续跟踪。

**Comment by huanghone** [comment]
@CNchence  在开始跟踪前，写一段手动调整姿态的程序，对应键盘的某些键调整6个姿态参数并用render类实时的画出模型，不断调整参数直到画出的模型与图像中的物体重合为止，这样就能得到初始帧参数了。
