### ISSUE TITLE
Port in OpenCV contrib

### ISSUE THREAD

**Issue by paroj** [guofengw/GOSTracker#6]
I have finally found the time to integrate this into OpenCV. See:
https://github.com/opencv/opencv_contrib/tree/master/modules/rapid

Here, I ended up rewriting most of the code, but having your code for comparison was a nice help nevertheless.

I found some bugs, which I wanted to note though (Off the top of my head)
- sometimes the search-lines were reversed, which led to mismatches
- your LOS implementation was using the background class for tracking
- you were initialising memory very inefficiently, which hampered runtime

Fixing these allows using the non-robust OpenCV pose-estimator instead of levmar with tuckey.
The version that is now in OpenCV is about 2-3x faster, while being more precise.

On the plus side, the non-robust estimator showcases the difference between GOS and LOS better.

**Comment by guofengw** [comment]
Thank you for your work.
I briefly browse the code, your implementation is very short and effective. 
I will study and review it.
